version: "3"
services:
  nginx:
    image: nginx
    restart: always
    container_name: client-nginx-172.4.0.70
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/srv/www/dist
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - /etc/localtime:/etc/localtime
    networks:
      default:
        ipv4_address: 172.4.0.70
networks:
  default:
    external:
      name: 2019_nCoV_network
