version: "3"
services:
  server:
    image: keymetrics/pm2
    container_name: server-node-172.4.0.80
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - .:/srv/docker-node
      - /etc/localtime:/etc/localtime
    command: pm2-runtime start /srv/docker-node/ecosystem.config.js
    networks:
      default:
        ipv4_address: 172.4.0.80
networks:
  default:
    external:
      name: 2019_nCoV_network
